### ISSUE TITLE
BookshelfModal 생성 시 이전 것과 완벽히 겹치지 않고 조금씩 위치 변경해서 뜨도록

### ISSUE THREAD

**Issue by junsushin-dev** [Team-Panopticon/bookmark-dashboard#33]
- [x] vue final modal 생성 위치를 변경
- [x] Modal 생성 시 Offset만큼 이동하여 적용
- [x] Modal 드래그 시 생성할 Offset의 기준값을 변경 (window의 스펙과 동일)
- [x] 새로 생길 모달의 위치가 viewport의 bottom right와 충돌하여 더 이상 이동할 수 없을 경우, default position으로 기준값 변경
   
   window 스펙은 top, right가 넘어갈 경우, top right를 각각 초기화
   ex) 생성될 폴더가 아래쪽으로 더이상 갈 곳이 없을 경우, `{ top: 0, right: currentright + OFFSET }`

**Comment by EarlyHail** [comment]
작업 브렌치는 [feat/bookshelf-modal-create-position](https://github.com/Team-Panopticon/bookmark-dashboard/tree/feat/bookshelf-modal-create-position) 입니다
